[package]
name = "json-dereferencer"
version = "0.1.0"
authors = ["duxet <duxetlg@gmail.com>"]

[dependencies]
glob = "0.2"
serde = "1.0"
serde_json = "1.0"

[dependencies.clap]
version = "2"
features = ["yaml"]